sudo: required
services:
  - docker

before_install:
  - docker build -t elmouradiamine/docker-react -f Dockerfile.dev .

script:
  - docker run elmouradiamine/docker-react npm run test:ci

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-reactr'
  env: 'Dockerreactr-env'
  bucket_name: 'elasticbeanstalk-us-east-2-012985200922'
  bucket_path: 'docker-reactr'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
